### ISSUE TITLE
ifThen() TODO

### ISSUE THREAD

**Issue by ifyio** [flute-io/routine#19]
- [ ] Should also work when conditions return promises
- [ ] Secondary operation should also be able to return a promise
- [ ] Test to ensure that `otherwise()` instance metadata is recognised
